//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuProjectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedTransaction
    {
        public int pk_transactionID { get; set; }
        public int fk_cartID { get; set; }
        public string fk_userName { get; set; }
        public int fk_paymentID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual PayInformation PayInformation { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
