//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuProjectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public string fk_userName { get; set; }
        public string streetAddress1 { get; set; }
        public string streetAddress2 { get; set; }
        public string city { get; set; }
        public string userState { get; set; }
        public int zip { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
